---
title: "Untitled"
author: "Yiran Liu"
date: "10/17/2019"
output: html_document
---

```{r}
install.packages('nycflights13')
library(nycflights13)
fl=nycflights13::flights
```

```{r}
#data processing
df = data.frame(fl$year,fl$month,fl$day,fl$sched_dep_time,fl$arr_delay,fl$carrier)
df$time <- cut(df$fl.sched_dep_time, breaks=c(0,459,1059,1659,2259,2359), labels=c("Late Night","Morning","Afternoon","Evening","Late Night"))
df$ontime <- ifelse(df$fl.arr_delay<=0&!is.na(df$fl.arr_delay), "On Time", "Not On Time")
tbl = table(df$ontime,df$time) 
tbl
chisq.test(tbl,correct=TRUE) 

```

```{r}
#table for Chi-squared test for independence
tbl <- cbind(tbl, Total = rowSums(tbl))
tbl<-rbind(tbl,Total = colSums(tbl))
tbl
```
$$
Conditional Probabilities\\
P(OnTime|Morning)=77401/114987=0.6731\\
P(OnTime|Afternoon)=68672/122766=0.5594\\
P(OnTime|Evening)=47769/97961=0.4876\\
P(OnTime|Late Night)=500/1062=0.4708
$$




```{r}
#arrival delay distribution
df$date <- with(df, ISOdate(year = 2013, df$fl.month, df$fl.day)) 
df$date = as.Date(format(df$date, "%Y-%m-%d"))
g <- ggplot(df, aes(x = df$date, y = df$fl.arr_delay, title="Time Peroid Trends")) 
g + geom_point(aes(color = df$time)) + xlab("Date") + ylab("Arrival Delay (mins)") + ggtitle("Time Peroid Trends")

```

```{r}
#conditional probabilites for each airline's on-time rate in each time periods
table = table(df$fl.carrier,df$ontime,df$time) 
Morning<-table[,,"Morning"]
Afternoon<-table[,,"Afternoon"]
Evening<-table[,,"Evening"]
Late_Night<-table[,,"Late Night"]

Morning<-as.data.frame.matrix(Morning) 
total_col = apply(Morning[,-10], 1, sum)
pcts = lapply(Morning[,-10], function(x) {
  x / total_col*100
})
pcts_Morning = as.data.frame(pcts)

pcts_Morning <- tibble::rownames_to_column(pcts_Morning, "Airline")

##afternoon
Afternoon<-as.data.frame.matrix(Afternoon) 
total_col_Afternoon = apply(Afternoon[,-10], 1, sum)
pcts_Afternoon = lapply(Afternoon[,-10], function(x) {
  x / total_col_Afternoon*100
})
pcts_Afternoon = as.data.frame(pcts_Afternoon)
pcts_Afternoon <- tibble::rownames_to_column(pcts_Afternoon, "Airline")

Evening<-as.data.frame.matrix(Evening) 
total_col_Evening = apply(Evening[,-10], 1, sum)
pcts_Evening = lapply(Evening[,-10], function(x) {
  x / total_col_Evening*100
})
pcts_Evening = as.data.frame(pcts_Evening)
pcts_Evening <- tibble::rownames_to_column(pcts_Evening, "Airline")


Late_Night<-as.data.frame.matrix(Late_Night) 
total_col_Late_Night = apply(Late_Night[,-10], 1, sum)
pcts_Late_Night = lapply(Late_Night[,-10], function(x) {
  x / total_col_Late_Night*100
})
pcts_Late_Night = as.data.frame(pcts_Late_Night)
pcts_Late_Night <- tibble::rownames_to_column(pcts_Late_Night, "Airline")


###bar
p<-ggplot(pcts_Morning, aes(x=reorder(pcts_Morning$Airline,-pcts_Morning$On.Time), y=pcts_Morning$On.Time, color=pcts_Morning$Airline)) +
  geom_bar(stat="identity", fill="white") + xlab("Airline") + ylab("On-Time Rate(%)") + ggtitle("Airlines On-Time Rate in the Morning")
p

p2<-ggplot(pcts_Afternoon, aes(x=reorder(pcts_Afternoon$Airline,-pcts_Afternoon$On.Time), y=pcts_Afternoon$On.Time, color=pcts_Afternoon$Airline)) +
  geom_bar(stat="identity", fill="white") + xlab("Airline") + ylab("On-Time Rate(%)") + ggtitle("Airlines On-Time Rate in the Afternoon")
p2

p3<-ggplot(pcts_Evening, aes(x=reorder(pcts_Evening$Airline,-pcts_Evening$On.Time), y=pcts_Evening$On.Time, color=pcts_Evening$Airline)) +
  geom_bar(stat="identity", fill="white") + xlab("Airline") + ylab("On-Time Rate(%)") + ggtitle("Airlines On-Time Rate in the Evening")
p3

p4<-ggplot(pcts_Late_Night, aes(x=reorder(pcts_Late_Night$Airline,-pcts_Late_Night$On.Time), y=pcts_Late_Night$On.Time, color=pcts_Late_Night$Airline)) +
  geom_bar(stat="identity", fill="white") + xlab("Airline") + ylab("On-Time Rate(%)") + ggtitle("Airlines On-Time Rate in the Late Night")


p
p2
p3
p4

```











